#!/usr/bin/env bash
# tools/demo/quickscan_demo.sh -- a fully-banded `ecdat quickscan` demo path.
#
# DEV-019 (docs/deviations.md) established that a bare certificate/keystore
# on disk legitimately cannot receive a risk band without a real observed
# TLS handshake: a certificate-derived ledger subject has no `signed_at`
# (only a handshake confirms one) and a keyUsage-derived confidentiality
# context has no negotiated `algorithm` (a keyUsage bit is a capability,
# never an observed usage -- CLAUDE.md's "Package presence = capability,
# never usage" rule). `quickscan --context ... --live-tls host:port` against
# a REAL listening TLS endpoint is the only combination that supplies both,
# so this script starts one (a local `openssl s_server` presenting the
# harness's own pay-edge certificate/key), points quickscan at it, and stops
# the server again -- nothing here invents a signed_at or an assumed
# negotiated algorithm; it only arranges for quickscan to observe a genuine
# one.
#
# This script is CI/demo TOOLING (tools/), not scanner code or a rule --
# CLAUDE.md's "no harness identifiers in src/ or rules/" rule does not cover
# tools/ (tools/ci/check_no_harness_identifiers.py's own SCAN_DIRS is
# [src, rules] only), and this script takes the harness checkout path as an
# explicit argument/env var rather than assuming a location, so it carries
# no hardcoded harness identifier of its own either.
#
# Usage:
#   tools/demo/quickscan_demo.sh <path-to-ecdat-harness> [quickscan output dir]
# or:
#   ECDAT_HARNESS_DIR=<path-to-ecdat-harness> tools/demo/quickscan_demo.sh
#
# Requires: a Windows/Git-Bash `openssl` (>= 3.5, for native ML-KEM hybrid
# groups -- this repo's dev machine has OpenSSL 3.5.4 at /mingw64/bin/openssl)
# on PATH, and the harness's generated PKI already built (memory note: never
# delete ecdat-harness/harness/build/out -- this script only READS it).
set -euo pipefail

HARNESS_DIR="${1:-${ECDAT_HARNESS_DIR:-}}"
OUT_DIR="${2:-${ECDAT_QUICKSCAN_OUT:-}}"
PORT="${ECDAT_DEMO_TLS_PORT:-8443}"
HOST="127.0.0.1"
KEYSTORE_PASSWORD="${ECDAT_DEMO_KEYSTORE_PASSWORD:-changeit}"

if [[ -z "${HARNESS_DIR}" ]]; then
  echo "usage: $0 <path-to-ecdat-harness> [out-dir]" >&2
  echo "  (or set ECDAT_HARNESS_DIR)" >&2
  exit 2
fi

TARGETS_DIR="${HARNESS_DIR}/targets"
PKI_DIR="${HARNESS_DIR}/harness/build/out/pay-edge"
CERT_CHAIN="${PKI_DIR}/pay-edge.pem"   # edge cert + intermediate CA (EC), generated by generate-pki.sh
CERT_KEY="${PKI_DIR}/key.pem"          # EC private key for the same edge cert

for path in "${TARGETS_DIR}" "${CERT_CHAIN}" "${CERT_KEY}"; do
  if [[ ! -e "${path}" ]]; then
    echo "quickscan_demo: expected path not found: ${path}" >&2
    echo "  (has harness/build/generate-pki.sh been run for this harness checkout?)" >&2
    exit 2
  fi
done

if [[ -z "${OUT_DIR}" ]]; then
  OUT_DIR="pramana-out/demo-$(date +%Y%m%dT%H%M%S)"
fi
mkdir -p "${OUT_DIR}"

OPENSSL_BIN="${ECDAT_OPENSSL_BIN:-openssl}"
if ! command -v "${OPENSSL_BIN}" >/dev/null 2>&1; then
  echo "quickscan_demo: openssl not found on PATH (set ECDAT_OPENSSL_BIN)" >&2
  exit 2
fi
"${OPENSSL_BIN}" version

SERVER_LOG="${OUT_DIR}/openssl_s_server.log"
echo "quickscan_demo: starting openssl s_server on ${HOST}:${PORT} (cert ${CERT_CHAIN})"
# -www: answer any request with a small status page, just enough for the
# handshake quickscan's tls-endpoint adapter probes to complete against.
# -groups: offer the same hybrid groups data/crypto_families.yaml already
# cites (X25519MLKEM768, SecP256r1MLKEM768, SecP384r1MLKEM1024) plus one
# classical control group, so a live probe can observe HYBRID_KEX.
"${OPENSSL_BIN}" s_server \
  -accept "${PORT}" \
  -cert "${CERT_CHAIN}" \
  -key "${CERT_KEY}" \
  -www \
  -groups X25519MLKEM768:SecP256r1MLKEM768:SecP384r1MLKEM1024:X25519 \
  >"${SERVER_LOG}" 2>&1 &
SERVER_PID=$!

cleanup() {
  if kill -0 "${SERVER_PID}" >/dev/null 2>&1; then
    echo "quickscan_demo: stopping openssl s_server (pid ${SERVER_PID})"
    kill "${SERVER_PID}" >/dev/null 2>&1 || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# Give s_server a moment to bind before probing it.
for _ in $(seq 1 20); do
  if "${OPENSSL_BIN}" s_client -connect "${HOST}:${PORT}" -brief </dev/null >/dev/null 2>&1; then
    break
  fi
  sleep 0.5
done

echo "quickscan_demo: running ecdat quickscan against ${TARGETS_DIR}"
python -m ecdat.cli quickscan "${TARGETS_DIR}" \
  --sector bfsi \
  --rollout-y-days 730 \
  --context example \
  --keystore-password "${KEYSTORE_PASSWORD}" \
  --live-tls "${HOST}:${PORT}" \
  --out "${OUT_DIR}"

echo "quickscan_demo: done -> ${OUT_DIR} (openssl s_server log: ${SERVER_LOG})"
